eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:18761/eureka/
      
      
logging:
  level:
    ROOT: INFO
#    com.netflix.eureka.registry.AbstractInstanceRegistry: WARN
#    com.netflix.discovery.DiscoveryClient: WARN      
